# Generated by Django 2.2.5 on 2021-02-28 14:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pauses', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), blank=True, null=True, size=None)),
                ('bookmarks', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), blank=True, null=True, size=None)),
                ('transcripts', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None)),
                ('transcript_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), blank=True, null=True, size=None)),
                ('returnpoints', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('transcript_time', models.TimeField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('subtitle_time', models.TimeField(blank=True, null=True)),
                ('intended_time', models.TimeField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('error_type', models.TextField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to='core.Session')),
            ],
        ),
    ]
